import type { ICountryCodes } from '@/types/countryCode.types';

export const CON_COUNTRY_FLAG_URL = 'https://newsapi.org/images/flags';
export const CON_COUNTRY_FLAG_IMAGE_EXTENSION = '.svg';

export const CON_COUNTRY_CODES: ICountryCodes = {
  af: { text: 'Afghanistan', key: 'af' },
  ax: { text: 'Åland Islands', key: 'ax' },
  al: { text: 'Albania', key: 'al' },
  dz: { text: 'Algeria', key: 'dz' },
  as: { text: 'American Samoa', key: 'as' },
  ad: { text: 'Andorra', key: 'ad' },
  ao: { text: 'Angola', key: 'ao' },
  ai: { text: 'Anguilla', key: 'ai' },
  aq: { text: 'Antarctica', key: 'aq' },
  ag: { text: 'Antigua and Barbuda', key: 'ag' },
  ar: { text: 'Argentina', key: 'ar' },
  am: { text: 'Armenia', key: 'am' },
  aw: { text: 'Aruba', key: 'aw' },
  au: { text: 'Australia', key: 'au' },
  at: { text: 'Austria', key: 'at' },
  az: { text: 'Azerbaijan', key: 'az' },
  bs: { text: 'Bahamas', key: 'bs' },
  bh: { text: 'Bahrain', key: 'bh' },
  bd: { text: 'Bangladesh', key: 'bd' },
  bb: { text: 'Barbados', key: 'bb' },
  by: { text: 'Belarus', key: 'by' },
  be: { text: 'Belgium', key: 'be' },
  bz: { text: 'Belize', key: 'bz' },
  bj: { text: 'Benin', key: 'bj' },
  bm: { text: 'Bermuda', key: 'bm' },
  bt: { text: 'Bhutan', key: 'bt' },
  bo: { text: 'Bolivia, Plurinational State of', key: 'bo' },
  bq: { text: 'Bonaire, Sint Eustatius and Saba', key: 'bq' },
  ba: { text: 'Bosnia and Herzegovina', key: 'ba' },
  bw: { text: 'Botswana', key: 'bw' },
  bv: { text: 'Bouvet Island', key: 'bv' },
  br: { text: 'Brazil', key: 'br' },
  io: { text: 'British Indian Ocean Territory', key: 'io' },
  bn: { text: 'Brunei Darussalam', key: 'bn' },
  bg: { text: 'Bulgaria', key: 'bg' },
  bf: { text: 'Burkina Faso', key: 'bf' },
  bi: { text: 'Burundi', key: 'bi' },
  kh: { text: 'Cambodia', key: 'kh' },
  cm: { text: 'Cameroon', key: 'cm' },
  ca: { text: 'Canada', key: 'ca' },
  cv: { text: 'Cape Verde', key: 'cv' },
  ky: { text: 'Cayman Islands', key: 'ky' },
  cf: { text: 'Central African Republic', key: 'cf' },
  td: { text: 'Chad', key: 'td' },
  cl: { text: 'Chile', key: 'cl' },
  cn: { text: 'China', key: 'cn' },
  cx: { text: 'Christmas Island', key: 'cx' },
  cc: { text: 'Cocos (Keeling) Islands', key: 'cc' },
  co: { text: 'Colombia', key: 'co' },
  km: { text: 'Comoros', key: 'km' },
  cg: { text: 'Congo', key: 'cg' },
  cd: { text: 'Congo, the Democratic Republic of the', key: 'cd' },
  ck: { text: 'Cook Islands', key: 'ck' },
  cr: { text: 'Costa Rica', key: 'cr' },
  ci: { text: "Côte d'Ivoire", key: 'ci' },
  hr: { text: 'Croatia', key: 'hr' },
  cu: { text: 'Cuba', key: 'cu' },
  cw: { text: 'Curaçao', key: 'cw' },
  cy: { text: 'Cyprus', key: 'cy' },
  cz: { text: 'Czech Republic', key: 'cz' },
  dk: { text: 'Denmark', key: 'dk' },
  dj: { text: 'Djibouti', key: 'dj' },
  dm: { text: 'Dominica', key: 'dm' },
  do: { text: 'Dominican Republic', key: 'do' },
  ec: { text: 'Ecuador', key: 'ec' },
  eg: { text: 'Egypt', key: 'eg' },
  sv: { text: 'El Salvador', key: 'sv' },
  gq: { text: 'Equatorial Guinea', key: 'gq' },
  er: { text: 'Eritrea', key: 'er' },
  ee: { text: 'Estonia', key: 'ee' },
  et: { text: 'Ethiopia', key: 'et' },
  fk: { text: 'Falkland Islands (Malvinas)', key: 'fk' },
  fo: { text: 'Faroe Islands', key: 'fo' },
  fj: { text: 'Fiji', key: 'fj' },
  fi: { text: 'Finland', key: 'fi' },
  fr: { text: 'France', key: 'fr' },
  gf: { text: 'French Guiana', key: 'gf' },
  pf: { text: 'French Polynesia', key: 'pf' },
  tf: { text: 'French Southern Territories', key: 'tf' },
  ga: { text: 'Gabon', key: 'ga' },
  gm: { text: 'Gambia', key: 'gm' },
  ge: { text: 'Georgia', key: 'ge' },
  de: { text: 'Germany', key: 'de' },
  gh: { text: 'Ghana', key: 'gh' },
  gi: { text: 'Gibraltar', key: 'gi' },
  gr: { text: 'Greece', key: 'gr' },
  gl: { text: 'Greenland', key: 'gl' },
  gd: { text: 'Grenada', key: 'gd' },
  gp: { text: 'Guadeloupe', key: 'gp' },
  gu: { text: 'Guam', key: 'gu' },
  gt: { text: 'Guatemala', key: 'gt' },
  gg: { text: 'Guernsey', key: 'gg' },
  gn: { text: 'Guinea', key: 'gn' },
  gw: { text: 'Guinea-Bissau', key: 'gw' },
  gy: { text: 'Guyana', key: 'gy' },
  ht: { text: 'Haiti', key: 'ht' },
  hm: { text: 'Heard Island and McDonald Islands', key: 'hm' },
  va: { text: 'Holy See (Vatican City State)', key: 'va' },
  hn: { text: 'Honduras', key: 'hn' },
  hk: { text: 'Hong Kong', key: 'hk' },
  hu: { text: 'Hungary', key: 'hu' },
  is: { text: 'Iceland', key: 'is' },
  in: { text: 'India', key: 'in' },
  id: { text: 'Indonesia', key: 'id' },
  ir: { text: 'Iran, Islamic Republic of', key: 'ir' },
  iq: { text: 'Iraq', key: 'iq' },
  ie: { text: 'Ireland', key: 'ie' },
  im: { text: 'Isle of Man', key: 'im' },
  il: { text: 'Israel', key: 'il' },
  it: { text: 'Italy', key: 'it' },
  jm: { text: 'Jamaica', key: 'jm' },
  jp: { text: 'Japan', key: 'jp' },
  je: { text: 'Jersey', key: 'je' },
  jo: { text: 'Jordan', key: 'jo' },
  kz: { text: 'Kazakhstan', key: 'kz' },
  ke: { text: 'Kenya', key: 'ke' },
  ki: { text: 'Kiribati', key: 'ki' },
  kp: { text: "Korea, Democratic People's Republic of", key: 'kp' },
  kr: { text: 'Korea, Republic of', key: 'kr' },
  kw: { text: 'Kuwait', key: 'kw' },
  kg: { text: 'Kyrgyzstan', key: 'kg' },
  la: { text: "Lao People's Democratic Republic", key: 'la' },
  lv: { text: 'Latvia', key: 'lv' },
  lb: { text: 'Lebanon', key: 'lb' },
  ls: { text: 'Lesotho', key: 'ls' },
  lr: { text: 'Liberia', key: 'lr' },
  ly: { text: 'Libya', key: 'ly' },
  li: { text: 'Liechtenstein', key: 'li' },
  lt: { text: 'Lithuania', key: 'lt' },
  lu: { text: 'Luxembourg', key: 'lu' },
  mo: { text: 'Macao', key: 'mo' },
  mk: { text: 'Macedonia, the Former Yugoslav Republic of', key: 'mk' },
  mg: { text: 'Madagascar', key: 'mg' },
  mw: { text: 'Malawi', key: 'mw' },
  my: { text: 'Malaysia', key: 'my' },
  mv: { text: 'Maldives', key: 'mv' },
  ml: { text: 'Mali', key: 'ml' },
  mt: { text: 'Malta', key: 'mt' },
  mh: { text: 'Marshall Islands', key: 'mh' },
  mq: { text: 'Martinique', key: 'mq' },
  mr: { text: 'Mauritania', key: 'mr' },
  mu: { text: 'Mauritius', key: 'mu' },
  yt: { text: 'Mayotte', key: 'yt' },
  mx: { text: 'Mexico', key: 'mx' },
  fm: { text: 'Micronesia, Federated States of', key: 'fm' },
  md: { text: 'Moldova, Republic of', key: 'md' },
  mc: { text: 'Monaco', key: 'mc' },
  mn: { text: 'Mongolia', key: 'mn' },
  me: { text: 'Montenegro', key: 'me' },
  ms: { text: 'Montserrat', key: 'ms' },
  ma: { text: 'Morocco', key: 'ma' },
  mz: { text: 'Mozambique', key: 'mz' },
  mm: { text: 'Myanmar', key: 'mm' },
  na: { text: 'Namibia', key: 'na' },
  nr: { text: 'Nauru', key: 'nr' },
  np: { text: 'Nepal', key: 'np' },
  nl: { text: 'Netherlands', key: 'nl' },
  nc: { text: 'New Caledonia', key: 'nc' },
  nz: { text: 'New Zealand', key: 'nz' },
  ni: { text: 'Nicaragua', key: 'ni' },
  ne: { text: 'Niger', key: 'ne' },
  ng: { text: 'Nigeria', key: 'ng' },
  nu: { text: 'Niue', key: 'nu' },
  nf: { text: 'Norfolk Island', key: 'nf' },
  mp: { text: 'Northern Mariana Islands', key: 'mp' },
  no: { text: 'Norway', key: 'no' },
  om: { text: 'Oman', key: 'om' },
  pk: { text: 'Pakistan', key: 'pk' },
  pw: { text: 'Palau', key: 'pw' },
  ps: { text: 'Palestine, State of', key: 'ps' },
  pa: { text: 'Panama', key: 'pa' },
  pg: { text: 'Papua New Guinea', key: 'pg' },
  py: { text: 'Paraguay', key: 'py' },
  pe: { text: 'Peru', key: 'pe' },
  ph: { text: 'Philippines', key: 'ph' },
  pn: { text: 'Pitcairn', key: 'pn' },
  pl: { text: 'Poland', key: 'pl' },
  pt: { text: 'Portugal', key: 'pt' },
  pr: { text: 'Puerto Rico', key: 'pr' },
  qa: { text: 'Qatar', key: 'qa' },
  re: { text: 'Réunion', key: 're' },
  ro: { text: 'Romania', key: 'ro' },
  ru: { text: 'Russian Federation', key: 'ru' },
  rw: { text: 'Rwanda', key: 'rw' },
  bl: { text: 'Saint Barthélemy', key: 'bl' },
  sh: { text: 'Saint Helena, Ascension and Tristan da Cunha', key: 'sh' },
  kn: { text: 'Saint Kitts and Nevis', key: 'kn' },
  lc: { text: 'Saint Lucia', key: 'lc' },
  mf: { text: 'Saint Martin (French part)', key: 'mf' },
  pm: { text: 'Saint Pierre and Miquelon', key: 'pm' },
  vc: { text: 'Saint Vincent and the Grenadines', key: 'vc' },
  ws: { text: 'Samoa', key: 'ws' },
  sm: { text: 'San Marino', key: 'sm' },
  st: { text: 'Sao Tome and Principe', key: 'st' },
  sa: { text: 'Saudi Arabia', key: 'sa' },
  sn: { text: 'Senegal', key: 'sn' },
  rs: { text: 'Serbia', key: 'rs' },
  sc: { text: 'Seychelles', key: 'sc' },
  sl: { text: 'Sierra Leone', key: 'sl' },
  sg: { text: 'Singapore', key: 'sg' },
  sx: { text: 'Sint Maarten (Dutch part)', key: 'sx' },
  sk: { text: 'Slovakia', key: 'sk' },
  si: { text: 'Slovenia', key: 'si' },
  sb: { text: 'Solomon Islands', key: 'sb' },
  so: { text: 'Somalia', key: 'so' },
  za: { text: 'South Africa', key: 'za' },
  gs: { text: 'South Georgia and the South Sandwich Islands', key: 'gs' },
  ss: { text: 'South Sudan', key: 'ss' },
  es: { text: 'Spain', key: 'es' },
  lk: { text: 'Sri Lanka', key: 'lk' },
  sd: { text: 'Sudan', key: 'sd' },
  sr: { text: 'Suriname', key: 'sr' },
  sj: { text: 'Svalbard and Jan Mayen', key: 'sj' },
  sz: { text: 'Eswatini', key: 'sz' },
  se: { text: 'Sweden', key: 'se' },
  ch: { text: 'Switzerland', key: 'ch' },
  sy: { text: 'Syrian Arab Republic', key: 'sy' },
  tw: { text: 'Taiwan, Province of China', key: 'tw' },
  tj: { text: 'Tajikistan', key: 'tj' },
  tz: { text: 'Tanzania, United Republic of', key: 'tz' },
  th: { text: 'Thailand', key: 'th' },
  tl: { text: 'Timor-Leste', key: 'tl' },
  tg: { text: 'Togo', key: 'tg' },
  tk: { text: 'Tokelau', key: 'tk' },
  to: { text: 'Tonga', key: 'to' },
  tt: { text: 'Trinidad and Tobago', key: 'tt' },
  tn: { text: 'Tunisia', key: 'tn' },
  tr: { text: 'Turkey', key: 'tr' },
  tm: { text: 'Turkmenistan', key: 'tm' },
  tc: { text: 'Turks and Caicos Islands', key: 'tc' },
  tv: { text: 'Tuvalu', key: 'tv' },
  ug: { text: 'Uganda', key: 'ug' },
  ua: { text: 'Ukraine', key: 'ua' },
  ae: { text: 'United Arab Emirates', key: 'ae' },
  gb: { text: 'United Kingdom', key: 'gb' },
  us: { text: 'United States', key: 'us' },
  um: { text: 'United States Minor Outlying Islands', key: 'um' },
  uy: { text: 'Uruguay', key: 'uy' },
  uz: { text: 'Uzbekistan', key: 'uz' },
  vu: { text: 'Vanuatu', key: 'vu' },
  ve: { text: 'Venezuela, Bolivarian Republic of', key: 've' },
  vn: { text: 'Viet Nam', key: 'vn' },
  vg: { text: 'Virgin Islands, British', key: 'vg' },
  vi: { text: 'Virgin Islands, U.S.', key: 'vi' },
  wf: { text: 'Wallis and Futuna', key: 'wf' },
  eh: { text: 'Western Sahara', key: 'eh' },
  ye: { text: 'Yemen', key: 'ye' },
  zm: { text: 'Zambia', key: 'zm' },
  zw: { text: 'Zimbabwe', key: 'zw' },
};
